# Generated by Django 5.1.7 on 2025-03-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatsessions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessions',
            name='name',
            field=models.CharField(default='chat created', max_length=1000),
            preserve_default=False,
        ),
    ]
