# Generated by Django 5.1.7 on 2025-03-16 11:16

import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', support.models.CompressedImageField(quality=75, upload_to=support.models.CompressedImageField.get_content_file_path, width=1920)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Article Categories',
            },
        ),
    ]
