# Generated by Django 5.1.7 on 2025-03-20 07:39

import support.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=support.models.CompressedImageField(quality=75, upload_to=support.models.CompressedImageField.get_content_file_path, width=1920),
        ),
    ]
