# Generated by Django 5.1.7 on 2025-03-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articleimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
