# Generated by Django 5.1.7 on 2025-03-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
